name: home-assistant-setup

services:
    mqtt:
        image: eclipse-mosquitto
        restart: unless-stopped
        volumes: 
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/log:/mosquitto/log

    zigbee:
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        ports:
            - 8124:8080
        volumes:
            - ./zigbee2mqtt/data:/app/data
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyUSB0:/dev/ttyACM0
        depends_on:
            - mqtt
            
    hass:
       image: ghcr.io/home-assistant/home-assistant:stable
       restart: unless-stopped
       ports:
            - 8123:8123
       volumes:
           - ./hass:/config
           - ./hass/localtime:/etc/localtime:ro
           - /run/dbus:/run/dbus:ro
       privileged: true
       depends_on:
           - mqtt
           - zigbee
