name: hass

services:
    tailscale:
        container_name: tailscale_vpn
        image: tailscale/tailscale:latest
        hostname: vpn
        restart: unless-stopped
        environment:
            - TS_AUTHKEY=<SUPER_SECRET_API_KEY>?ephemeral=false
            - TS_EXTRA_ARGS=--advertise-tags=tag:container
            - TS_SERVE_CONFIG=/config/serve.json
            - TS_STATE_DIR=/var/lib/tailscale
        volumes:
            - ./tailscale/state:/var/lib/tailscale
            - ./tailscale/config:/config
            - /dev/net/tun:/dev/net/tun
        ports:
            - 8123:8123
            - 8124:8080
            - 9001:9001
            - 1883:1883
        cap_add:
            - net_admin
            - sys_module
        
    mosquitto:
        container_name: mosquitto-mqtt-broker
        image: eclipse-mosquitto
        restart: unless-stopped
        volumes: 
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/log:/mosquitto/log
        depends_on:
            - tailscale
        network_mode: service:tailscale

    zigbee2mqtt:
        container_name: zigbee2mqtt_adapter
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - ./zigbee2mqtt/data:/app/data
            - /run/udev:/run/udev:ro
        devices:
            - /dev/ttyUSB0:/dev/ttyACM0
        depends_on:
            - mosquitto
            - tailscale
        network_mode: service:tailscale
    
    homeassistant:
       container_name: home_assistant
       image: ghcr.io/home-assistant/home-assistant:stable
       restart: unless-stopped
       volumes:
           - ./HomeAssistant:/config
           - ./HomeAssistant/localtime:/etc/localtime:ro
           - /run/dbus:/run/dbus:ro
       privileged: true
       depends_on:
           - mosquitto
           - zigbee2mqtt
           - tailscale
       network_mode: service:tailscale
